<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends EntityRepository
{

    public function findHomeTitle(){
        $qb=$this->createQueryBuilder("a");

        $query=$qb
            ->setMaxResults(1)
            ->getQuery();

        return $query->getSingleResult();
    }
}
